### ISSUE TITLE
Error analyzing with stylelint

### ISSUE THREAD

**Issue by ljmf00** [codacy/codacy-stylelint#18]
Log:
```
CSS :

Docker exited with code 1
stdout: 
stderr: WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Error executing the tool
java.lang.Exception: Could not parse results json: Unrecognized token 'Error': was expecting ('true', 'false' or 'null')
 at [Source: Error: Could not find "stylelint-a11y". Do you need a `configBasedir`?
    at module.exports (/usr/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at getModulePath (/usr/lib/node_modules/stylelint/lib/utils/getModulePath.js:26:11)
    at config.plugins.concat.map.lookup (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:123:14)
    at Array.map (<anonymous>)
    at absolutizePaths (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:122:48)
    at Promise.resolve.then.then.then.augmentedConfig (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:32:14); line: 1, column: 6]

Json:
Error: Could not find "stylelint-a11y". Do you need a `configBasedir`?
    at module.exports (/usr/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at getModulePath (/usr/lib/node_modules/stylelint/lib/utils/getModulePath.js:26:11)
    at config.plugins.concat.map.lookup (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:123:14)
    at Array.map (<anonymous>)
    at absolutizePaths (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:122:48)
    at Promise.resolve.then.then.then.augmentedConfig (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:32:14)
              
	at codacy.stylelint.Stylelint$$anonfun$$nestedInanonfun$parseJson$1$1.applyOrElse(Stylelint.scala:91)
	at codacy.stylelint.Stylelint$$anonfun$$nestedInanonfun$parseJson$1$1.applyOrElse(Stylelint.scala:86)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recoverWith(Try.scala:236)
	at codacy.stylelint.Stylelint$.$anonfun$parseJson$1(Stylelint.scala:86)
	at scala.util.Success.flatMap(Try.scala:251)
	at codacy.stylelint.Stylelint$.parseJson(Stylelint.scala:84)
	at codacy.stylelint.Stylelint$.apply(Stylelint.scala:32)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:42)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2$adapted(DockerEngine.scala:28)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:28)
	at scala.util.Success.flatMap(Try.scala:251)
	at com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:27)
	at codacy.Engine.main(Engine.scala)
           
SASS :

Docker exited with code 1
stdout: 
stderr: WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Error executing the tool
java.lang.Exception: Could not parse results json: Unrecognized token 'Error': was expecting ('true', 'false' or 'null')
 at [Source: Error: Could not find "stylelint-a11y". Do you need a `configBasedir`?
    at module.exports (/usr/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at getModulePath (/usr/lib/node_modules/stylelint/lib/utils/getModulePath.js:26:11)
    at config.plugins.concat.map.lookup (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:123:14)
    at Array.map (<anonymous>)
    at absolutizePaths (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:122:48)
    at Promise.resolve.then.then.then.augmentedConfig (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:32:14); line: 1, column: 6]

Json:
Error: Could not find "stylelint-a11y". Do you need a `configBasedir`?
    at module.exports (/usr/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at getModulePath (/usr/lib/node_modules/stylelint/lib/utils/getModulePath.js:26:11)
    at config.plugins.concat.map.lookup (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:123:14)
    at Array.map (<anonymous>)
    at absolutizePaths (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:122:48)
    at Promise.resolve.then.then.then.augmentedConfig (/usr/lib/node_modules/stylelint/lib/augmentConfig.js:32:14)
              
	at codacy.stylelint.Stylelint$$anonfun$$nestedInanonfun$parseJson$1$1.applyOrElse(Stylelint.scala:91)
	at codacy.stylelint.Stylelint$$anonfun$$nestedInanonfun$parseJson$1$1.applyOrElse(Stylelint.scala:86)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recoverWith(Try.scala:236)
	at codacy.stylelint.Stylelint$.$anonfun$parseJson$1(Stylelint.scala:86)
	at scala.util.Success.flatMap(Try.scala:251)
	at codacy.stylelint.Stylelint$.parseJson(Stylelint.scala:84)
	at codacy.stylelint.Stylelint$.apply(Stylelint.scala:32)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:42)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2$adapted(DockerEngine.scala:28)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:28)
	at scala.util.Success.flatMap(Try.scala:251)
	at com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:27)
	at codacy.Engine.main(Engine.scala)
```

**Comment by mrfyda** [comment]
@ljmf00 where is this log from?
L
ooks like we are missing the `stylelint-a11y` plugin
