### ISSUE TITLE
Stylelint is missing postCSS plugin

### ISSUE THREAD

**Issue by ljmf00** [codacy/codacy-stylelint#23]
When running stylelint on Wordpress project, it fails:

```
CSS :

KubernetesDockerRunner: Container for codacy/codacy-stylelint:2.3.0 exited with non-zero code 1
Error executing the tool
java.lang.Exception: Could not parse results json: Unrecognized token 'Error': was expecting ('true', 'false' or 'null')
 at [Source: Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/usr/lib/node_modules/stylelint/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/usr/lib/node_modules/stylelint-a11y/dist/rules/media-prefers-reduced-motion/index.js:80:16)
    at Module._compile (/usr/lib/node_modules/stylelint/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3); line: 1, column: 6]

Json:
Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/usr/lib/node_modules/stylelint/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/usr/lib/node_modules/stylelint-a11y/dist/rules/media-prefers-reduced-motion/index.js:80:16)
    at Module._compile (/usr/lib/node_modules/stylelint/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
              
	at codacy.stylelint.Stylelint$$anonfun$$nestedInanonfun$parseJson$1$1.applyOrElse(Stylelint.scala:91)
	at codacy.stylelint.Stylelint$$anonfun$$nestedInanonfun$parseJson$1$1.applyOrElse(Stylelint.scala:86)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recoverWith(Try.scala:236)
	at codacy.stylelint.Stylelint$.$anonfun$parseJson$1(Stylelint.scala:86)
	at scala.util.Success.flatMap(Try.scala:251)
	at codacy.stylelint.Stylelint$.parseJson(Stylelint.scala:84)
	at codacy.stylelint.Stylelint$.apply(Stylelint.scala:32)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:42)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2$adapted(DockerEngine.scala:28)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:28)
	at scala.util.Success.flatMap(Try.scala:251)
	at com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:27)
	at codacy.Engine.main(Engine.scala)

SASS :

KubernetesDockerRunner: Container for codacy/codacy-stylelint:2.3.0 exited with non-zero code 1
Error executing the tool
java.lang.Exception: Could not parse results json: Unrecognized token 'Error': was expecting ('true', 'false' or 'null')
 at [Source: Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/usr/lib/node_modules/stylelint/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/usr/lib/node_modules/stylelint-a11y/dist/rules/media-prefers-reduced-motion/index.js:80:16)
    at Module._compile (/usr/lib/node_modules/stylelint/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3); line: 1, column: 6]

Json:
Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/usr/lib/node_modules/stylelint/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/usr/lib/node_modules/stylelint-a11y/dist/rules/media-prefers-reduced-motion/index.js:80:16)
    at Module._compile (/usr/lib/node_modules/stylelint/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
              
	at codacy.stylelint.Stylelint$$anonfun$$nestedInanonfun$parseJson$1$1.applyOrElse(Stylelint.scala:91)
	at codacy.stylelint.Stylelint$$anonfun$$nestedInanonfun$parseJson$1$1.applyOrElse(Stylelint.scala:86)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recoverWith(Try.scala:236)
	at codacy.stylelint.Stylelint$.$anonfun$parseJson$1(Stylelint.scala:86)
	at scala.util.Success.flatMap(Try.scala:251)
	at codacy.stylelint.Stylelint$.parseJson(Stylelint.scala:84)
	at codacy.stylelint.Stylelint$.apply(Stylelint.scala:32)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2(DockerEngine.scala:42)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$2$adapted(DockerEngine.scala:28)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at com.codacy.tools.scala.seed.DockerEngine.$anonfun$main$1(DockerEngine.scala:28)
	at scala.util.Success.flatMap(Try.scala:251)
	at com.codacy.tools.scala.seed.DockerEngine.main(DockerEngine.scala:27)
	at codacy.Engine.main(Engine.scala)
```

**Comment by mrfyda** [comment]
Looks like we are missing the postcss plugin:
https://stylelint.io/user-guide/postcss-plugin
